using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Repository.Migrations
{
    /// <inheritdoc />
    public partial class MakeKeyAutoGeneratedForAllEntites : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_BookFavouriteList_FavouriteList_FavouritesId",
                table: "BookFavouriteList");

            migrationBuilder.DropForeignKey(
                name: "FK_FavouriteList_AspNetUsers_AppUserId",
                table: "FavouriteList");

            migrationBuilder.DropPrimaryKey(
                name: "PK_FavouriteList",
                table: "FavouriteList");

            migrationBuilder.RenameTable(
                name: "FavouriteList",
                newName: "FavouriteLists");

            migrationBuilder.RenameIndex(
                name: "IX_FavouriteList_AppUserId",
                table: "FavouriteLists",
                newName: "IX_FavouriteLists_AppUserId");

            migrationBuilder.AlterColumn<int>(
                name: "CategoryId",
                table: "Books",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            migrationBuilder.AddPrimaryKey(
                name: "PK_FavouriteLists",
                table: "FavouriteLists",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_BookFavouriteList_FavouriteLists_FavouritesId",
                table: "BookFavouriteList",
                column: "FavouritesId",
                principalTable: "FavouriteLists",
                principalColumn: "Id",
                onDelete: ReferentialAction.NoAction);

            migrationBuilder.AddForeignKey(
                name: "FK_FavouriteLists_AspNetUsers_AppUserId",
                table: "FavouriteLists",
                column: "AppUserId",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.NoAction);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_BookFavouriteList_FavouriteLists_FavouritesId",
                table: "BookFavouriteList");

            migrationBuilder.DropForeignKey(
                name: "FK_FavouriteLists_AspNetUsers_AppUserId",
                table: "FavouriteLists");

            migrationBuilder.DropPrimaryKey(
                name: "PK_FavouriteLists",
                table: "FavouriteLists");

            migrationBuilder.RenameTable(
                name: "FavouriteLists",
                newName: "FavouriteList");

            migrationBuilder.RenameIndex(
                name: "IX_FavouriteLists_AppUserId",
                table: "FavouriteList",
                newName: "IX_FavouriteList_AppUserId");

            migrationBuilder.AlterColumn<int>(
                name: "CategoryId",
                table: "Books",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_FavouriteList",
                table: "FavouriteList",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_BookFavouriteList_FavouriteList_FavouritesId",
                table: "BookFavouriteList",
                column: "FavouritesId",
                principalTable: "FavouriteList",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_FavouriteList_AspNetUsers_AppUserId",
                table: "FavouriteList",
                column: "AppUserId",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
